.TH "Содержание директории Documents/Student_rates_server" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории Documents/Student_rates_server
.SH SYNOPSIS
.br
.PP
.SS "Директории"

.in +1c
.ti -1c
.RI "директория \fBserver\fP"
.br
.in -1c
