.TH "Содержание директории Documents/Student_rates_server/server" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории Documents/Student_rates_server/server
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBserver\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBserver\&.h\fP"
.br
.in -1c
