.TH "C:/Users/Danila/Documents/Student_rates_server/main.cpp" 3 "Пн 28 Дек 2020" "Клиент-серверное приложение по учёту студентов (серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Danila/Documents/Student_rates_server/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QCoreApplication>\fP
.br
\fC#include 'server/server\&.h'\fP
.br

.SS "Функции"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Функции"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Клиент-серверное приложение по учёту студентов (серверная часть) из исходного текста\&.
