.TH "myserver" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myserver \- Класс принимает запросы от клиента, делает запросы к БД, отправляет клиенту ответ  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.PP
Базовые классы:QTcpServer\&.
.SS "Открытые слоты"

.in +1c
.ti -1c
.RI "void \fBstartServer\fP ()"
.br
.RI "Вызывается в методе main при запуске приложения\&. В методе создается экзмепляр QSqlDatabase\&. Устнавливается название БД\&. После этого идут 7 запросов к этой БД, которые создают таблицы, если он не созданы (создание таблиц происходит, когда программа впервые запускается на этом компьютере)\&. "
.ti -1c
.RI "void \fBincomingConnection\fP (qintptr socketDescriptor)"
.br
.RI "Виртуальная функция из класса QtcpServer, она вызывается, когда доспутно новое соединение\&. Внутри функции создается сокет и ему устанавливается дескриптор, полученный как параметр\&. "
.ti -1c
.RI "void \fBsockReady\fP ()"
.br
.ti -1c
.RI "void \fBsockDisc\fP ()"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBmyserver\fP ()"
.br
.RI "myserver Конструктор "
.ti -1c
.RI "\fB~myserver\fP ()"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс принимает запросы от клиента, делает запросы к БД, отправляет клиенту ответ 
.SH "Конструктор(ы)"
.PP 
.SS "myserver::myserver ()"

.PP
myserver Конструктор 
.SS "myserver::~myserver ()"

.SH "Методы"
.PP 
.SS "void myserver::incomingConnection (qintptr socketDescriptor)\fC [slot]\fP"

.PP
Виртуальная функция из класса QtcpServer, она вызывается, когда доспутно новое соединение\&. Внутри функции создается сокет и ему устанавливается дескриптор, полученный как параметр\&. 
.PP
\fBАргументы\fP
.RS 4
\fIsocketDescriptor\fP дескриптор сокета 
.RE
.PP

.SS "void myserver::sockDisc ()\fC [slot]\fP"

.SS "void myserver::sockReady ()\fC [slot]\fP"

.SS "void myserver::startServer ()\fC [slot]\fP"

.PP
Вызывается в методе main при запуске приложения\&. В методе создается экзмепляр QSqlDatabase\&. Устнавливается название БД\&. После этого идут 7 запросов к этой БД, которые создают таблицы, если он не созданы (создание таблиц происходит, когда программа впервые запускается на этом компьютере)\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(серверная часть) из исходного текста\&.
