.TH "Documents/Student_rates_server/server/server.cpp" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/Student_rates_server/server/server.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'server\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(серверная часть) из исходного текста\&.
