.TH "Documents/Student_rates_server/server/server.h" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(серверная часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/Student_rates_server/server/server.h
.SH SYNOPSIS
.br
.PP
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QJsonParseError>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QTcpSocket>\fP
.br
\fC#include <QTcpServer>\fP
.br
\fC#include <QSqlDatabase>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QDir>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmyserver\fP"
.br
.RI "Класс принимает запросы от клиента, делает запросы к БД, отправляет клиенту ответ "
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(серверная часть) из исходного текста\&.
