.TH "Содержание директории Documents/student_rates_client" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Содержание директории Documents/student_rates_client
.SH SYNOPSIS
.br
.PP
.SS "Файлы"

.in +1c
.ti -1c
.RI "файл \fBinput\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBinput\&.h\fP"
.br
.ti -1c
.RI "файл \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "файл \fBrateswindow\&.cpp\fP"
.br
.ti -1c
.RI "файл \fBrateswindow\&.h\fP"
.br
.in -1c
