.TH "MainWindow" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Базовые классы:QMainWindow\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "Ui::MainWindow * \fBui\fP"
.br
.in -1c
.SH "Конструктор(ы)"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fCnullptr\fP)"

.SS "MainWindow::~MainWindow ()"

.SH "Данные класса"
.PP 
.SS "Ui::MainWindow* MainWindow::ui\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(Клиентская часть) из исходного текста\&.
