.TH "Documents/student_rates_client/mainwindow.h" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/student_rates_client/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(Клиентская часть) из исходного текста\&.
