.TH "RatesPage" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RatesPage \- The \fBRatesPage\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rateswindow\&.h>\fP
.PP
Базовые классы:QMainWindow\&.
.SS "Сигналы"

.in +1c
.ti -1c
.RI "void \fBgroups_for_add_lesson\fP (QJsonArray groups)"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBRatesPage\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~RatesPage\fP ()"
.br
.ti -1c
.RI "void \fBDisplay\fP ()"
.br
.in -1c
.SS "Открытые атрибуты"

.in +1c
.ti -1c
.RI "QTcpSocket * \fBsocket\fP =nullptr"
.br
.in -1c
.SS "Закрытые слоты"

.in +1c
.ti -1c
.RI "void \fBsockReady\fP ()"
.br
.ti -1c
.RI "void \fBsockDisc\fP ()"
.br
.ti -1c
.RI "void \fBon_SaveRateButton_clicked\fP ()"
.br
.RI "on_SaveRateButton_clicked РЎРѕС…СЂР°РЅСЏРµС‚ Р±Р°Р»Р» РІРІРµРґРµРЅРЅС‹Р№ РІ РїРѕР»Рµ РІРІРѕРґР° "
.ti -1c
.RI "void \fBon_choose_group_currentIndexChanged\fP (int index)"
.br
.RI "РњРµС‚РѕРґ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё РІС‹Р·С‹РІР°РµС‚СЃСЏ РїСЂРё СЃРјРµРЅРµ Р·РЅР°С‡РµРЅРёСЏ РІ РєРѕРјР±Рѕ-Р±РѕРєСЃРµ СЃ СѓС‡РµР±РЅС‹РјРё РіСЂСѓРїРїР°РјРё\&. РњРµС‚РѕРґ РґРµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° СЃРµСЂРІРµСЂ РґР»СЏ РїРѕР»СѓС‡РµРЅРёСЏ СЃС‚СѓРґРµРЅС‚РѕРІ Рё РєСѓСЂСЃРѕРІ РґР»СЏ РІС‹Р±СЂР°РЅРЅРѕР№ РіСЂСѓРїРїС‹ "
.ti -1c
.RI "void \fBon_choose_student_currentIndexChanged\fP (int index)"
.br
.ti -1c
.RI "void \fBon_choose_course_currentIndexChanged\fP (int index)"
.br
.ti -1c
.RI "void \fBon_choouselesson_currentIndexChanged\fP (int index)"
.br
.ti -1c
.RI "void \fBauthorizeUser\fP ()"
.br
.RI "authorizeUser РћС‚СЂР°РІР»СЏРµС‚ РґР°РЅРЅС‹Рµ Р°РІС‚РѕСЂРёР·Р°С†РёРё РЅР° СЃРµСЂРІРµСЂ "
.ti -1c
.RI "void \fBget_courses_for_add_lesson\fP (QString group_Id)"
.br
.RI "get_courses_for_add_lesson Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° СЃРµСЂРІРµСЂ РЅР° РїРѕР»СѓС‡РµРЅРёРµ СЃРїРёСЃРєР° РєСѓСЂСЃРѕРІ РґР»СЏ РѕРїСЂРµРґРµР»РµРЅРЅРѕР№ СѓС‡РµР±РЅРѕР№ РіСЂСѓРїРїС‹ "
.ti -1c
.RI "void \fBget_all_students\fP ()"
.br
.RI "get_all_students Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° РїРѕР»СѓС‡РµРЅРёРµ РІСЃРµС… СЃС‚СѓРґРµРЅС‚РѕРІ "
.ti -1c
.RI "void \fBgetCoursesForStudent\fP (int StudentId)"
.br
.ti -1c
.RI "void \fBgetLessonsForStudentAndCourse\fP (int student_Id, int course_Id)"
.br
.RI "getLessonsForStudentAndCourse Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° РїРѕР»СѓС‡РµРЅРёРµ СЃРїРёСЃРєР° Р·Р°РЅСЏС‚РёР№ "
.ti -1c
.RI "void \fBsetRateToStudentInGenerallist\fP (QString rate, int student_Id, int lesson_Id)"
.br
.RI "setRateToStudentInGenerallist - РЈСЃС‚Р°РЅР°РІР»СЏРІР°РµС‚ Р±Р°Р»Р» СЃС‚СѓРґРµРЅС‚Сѓ "
.ti -1c
.RI "void \fBon_AddLesoon_triggered\fP ()"
.br
.ti -1c
.RI "void \fBon_AddLesson_clicked\fP ()"
.br
.ti -1c
.RI "void \fBon_Main_Page_triggered\fP ()"
.br
.ti -1c
.RI "void \fBon_GeneralListStudent_triggered\fP ()"
.br
.ti -1c
.RI "void \fBon_ChooseStudent_AllStudent_currentIndexChanged\fP (int index)"
.br
.ti -1c
.RI "void \fBon_ChooesCourse_AllStudent_currentIndexChanged\fP (int index)"
.br
.ti -1c
.RI "void \fBon_ChooseGroupToAddLesson_currentIndexChanged\fP (int index)"
.br
.in -1c
.SS "Закрытые члены"

.in +1c
.ti -1c
.RI "int \fBCurrentGroup\fP ()"
.br
.RI "CurrentGroup\&. "
.ti -1c
.RI "int \fBCurrentStudent\fP ()"
.br
.RI "CurrentStudent\&. "
.ti -1c
.RI "int \fBCurrentCourse\fP ()"
.br
.ti -1c
.RI "int \fBCurrentLesson\fP ()"
.br
.ti -1c
.RI "QString \fBCurrentRate\fP ()"
.br
.ti -1c
.RI "void \fBsetData\fP (QComboBox *comboBox, QJsonArray arr)"
.br
.RI "setData СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚ РґР°РЅРЅС‹Рµ РєРѕРјР±Рѕ-Р±РѕРєСЃ "
.ti -1c
.RI "void \fBgetGroups\fP ()"
.br
.ti -1c
.RI "void \fBgetRates\fP (int, int)"
.br
.ti -1c
.RI "void \fBgetLessons\fP (int, int)"
.br
.ti -1c
.RI "void \fBsetAllStudents\fP (QJsonArray docArr)"
.br
.RI "setAllStudents - СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚ СЃС‚СѓРґРµРЅС‚РѕРІ РІ РєРѕРјР±Рѕ-Р±РѕРєСЃ "
.ti -1c
.RI "void \fBsetStudents\fP (QJsonArray docAr_students, QJsonArray docAr_couse)"
.br
.ti -1c
.RI "void \fBsetRates\fP (QString rate)"
.br
.ti -1c
.RI "void \fBsetAllRates\fP (QJsonArray docAr, int count_student)"
.br
.RI "setAllRates - СѓСЃС‚Р°РЅР°Р»РІРёРІР°РµС‚ РІ С‚Р°Р±Р»РёС†Сѓ Р±Р°Р»Р»С‹ СЃС‚СѓРґРµРЅС‚РѕРІ "
.ti -1c
.RI "void \fBresInput\fP (QString status)"
.br
.ti -1c
.RI "void \fBsetGroupsForAddLesson\fP (QJsonArray docArr)"
.br
.ti -1c
.RI "void \fBResultAddLesson\fP (QString result)"
.br
.ti -1c
.RI "void \fBResultSetRate\fP (QString result)"
.br
.in -1c
.SS "Закрытые данные"

.in +1c
.ti -1c
.RI "Ui::RatesPage * \fBui\fP"
.br
.ti -1c
.RI "\fBInput\fP \fBinput_window\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
The \fBRatesPage\fP class\&. 
.SH "Конструктор(ы)"
.PP 
.SS "RatesPage::RatesPage (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.SS "RatesPage::~RatesPage ()"

.SH "Методы"
.PP 
.SS "void RatesPage::authorizeUser ()\fC [private]\fP, \fC [slot]\fP"

.PP
authorizeUser РћС‚СЂР°РІР»СЏРµС‚ РґР°РЅРЅС‹Рµ Р°РІС‚РѕСЂРёР·Р°С†РёРё РЅР° СЃРµСЂРІРµСЂ 
.SS "int RatesPage::CurrentCourse ()\fC [private]\fP"

.SS "int RatesPage::CurrentGroup ()\fC [private]\fP"

.PP
CurrentGroup\&. 
.PP
\fBВозвращает\fP
.RS 4
РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ СѓС‡РµР±РЅРѕР№ РіСЂСѓРїРїС‹, РєРѕС‚РѕСЂР°СЏ РІС‹Р±СЂР°РЅР° РІ РєРѕРјР±Рѕ-Р±РѕРєСЃРµ 
.RE
.PP

.SS "int RatesPage::CurrentLesson ()\fC [private]\fP"

.SS "QString RatesPage::CurrentRate ()\fC [private]\fP"

.SS "int RatesPage::CurrentStudent ()\fC [private]\fP"

.PP
CurrentStudent\&. 
.PP
\fBВозвращает\fP
.RS 4
РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ СЃС‚СѓРґРµРЅС‚Р°, РєРѕС‚РѕСЂР°СЏ РІС‹Р±СЂР°РЅ РІ РєРѕРјР±Рѕ-Р±РѕРєСЃРµ 
.RE
.PP

.SS "void RatesPage::Display ()"

.SS "void RatesPage::get_all_students ()\fC [private]\fP, \fC [slot]\fP"

.PP
get_all_students Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° РїРѕР»СѓС‡РµРЅРёРµ РІСЃРµС… СЃС‚СѓРґРµРЅС‚РѕРІ 
.SS "void RatesPage::get_courses_for_add_lesson (QString group_Id)\fC [private]\fP, \fC [slot]\fP"

.PP
get_courses_for_add_lesson Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° СЃРµСЂРІРµСЂ РЅР° РїРѕР»СѓС‡РµРЅРёРµ СЃРїРёСЃРєР° РєСѓСЂСЃРѕРІ РґР»СЏ РѕРїСЂРµРґРµР»РµРЅРЅРѕР№ СѓС‡РµР±РЅРѕР№ РіСЂСѓРїРїС‹ 
.PP
\fBАргументы\fP
.RS 4
\fIgroup_Id\fP - РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ РіСЂСѓРїРїС‹, РґР»СЏ РєРѕС‚РѕСЂРѕР№ РїРѕР»СѓС‡Р°РµРј СЃРїРёСЃРѕРє РєСѓСЂСЃРѕРІ\&. 
.RE
.PP

.SS "void RatesPage::getCoursesForStudent (int StudentId)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::getGroups ()\fC [private]\fP"

.SS "void RatesPage::getLessons (int Group_Id, int Course_Id)\fC [private]\fP"

.SS "void RatesPage::getLessonsForStudentAndCourse (int student_Id, int course_Id)\fC [private]\fP, \fC [slot]\fP"

.PP
getLessonsForStudentAndCourse Р”РµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° РїРѕР»СѓС‡РµРЅРёРµ СЃРїРёСЃРєР° Р·Р°РЅСЏС‚РёР№ 
.PP
\fBАргументы\fP
.RS 4
\fIstudent_Id\fP - РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ СЃС‚СѓРґРµРЅС‚Р°\&. РџРѕР»СѓС‡РµРЅРЅС‹Рµ Р·Р°РЅСЏС‚РёСЏ РґРѕР»Р¶РЅС‹ РѕС‚РЅРѕСЃРёС‚СЊСЃСЏ Рє С‚РѕР№ Р¶Рµ СѓС‡РµР±РЅРѕР№ РіСЂСѓРїРїРµ С‡С‚Рѕ Рё СЃС‚СѓРґРµРЅС‚\&. 
.br
\fIcourse_Id\fP - РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ РєСѓСЂСЃР°, РїРѕ РєРѕС‚РѕСЂРѕРјСѓ РІС‹Р±РёСЂР°СЋС‚СЃСЏ Р·Р°РЅСЏС‚РёСЏ\&. 
.RE
.PP

.SS "void RatesPage::getRates (int Student_Id, int Lesson_Id)\fC [private]\fP"

.SS "void RatesPage::groups_for_add_lesson (QJsonArray groups)\fC [signal]\fP"

.SS "void RatesPage::on_AddLesoon_triggered ()\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_AddLesson_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_ChooesCourse_AllStudent_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_choose_course_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_choose_group_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.PP
РњРµС‚РѕРґ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё РІС‹Р·С‹РІР°РµС‚СЃСЏ РїСЂРё СЃРјРµРЅРµ Р·РЅР°С‡РµРЅРёСЏ РІ РєРѕРјР±Рѕ-Р±РѕРєСЃРµ СЃ СѓС‡РµР±РЅС‹РјРё РіСЂСѓРїРїР°РјРё\&. РњРµС‚РѕРґ РґРµР»Р°РµС‚ Р·Р°РїСЂРѕСЃ РЅР° СЃРµСЂРІРµСЂ РґР»СЏ РїРѕР»СѓС‡РµРЅРёСЏ СЃС‚СѓРґРµРЅС‚РѕРІ Рё РєСѓСЂСЃРѕРІ РґР»СЏ РІС‹Р±СЂР°РЅРЅРѕР№ РіСЂСѓРїРїС‹ 
.PP
\fBАргументы\fP
.RS 4
\fIindex\fP 
.RE
.PP

.SS "void RatesPage::on_choose_student_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_ChooseGroupToAddLesson_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_ChooseStudent_AllStudent_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_choouselesson_currentIndexChanged (int index)\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_GeneralListStudent_triggered ()\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_Main_Page_triggered ()\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::on_SaveRateButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.PP
on_SaveRateButton_clicked РЎРѕС…СЂР°РЅСЏРµС‚ Р±Р°Р»Р» РІРІРµРґРµРЅРЅС‹Р№ РІ РїРѕР»Рµ РІРІРѕРґР° 
.SS "void RatesPage::resInput (QString status)\fC [private]\fP"

.SS "void RatesPage::ResultAddLesson (QString result)\fC [private]\fP"

.SS "void RatesPage::ResultSetRate (QString result)\fC [private]\fP"

.SS "void RatesPage::setAllRates (QJsonArray docAr, int count_student)\fC [private]\fP"

.PP
setAllRates - СѓСЃС‚Р°РЅР°Р»РІРёРІР°РµС‚ РІ С‚Р°Р±Р»РёС†Сѓ Р±Р°Р»Р»С‹ СЃС‚СѓРґРµРЅС‚РѕРІ 
.PP
\fBАргументы\fP
.RS 4
\fIdocAr\fP - РЅР°Р±РѕСЂ СЃ РґР°РЅРЅС‹РјРё Рѕ Р±Р°Р»Р»Р°С… 
.br
\fIcount_student\fP - РєРѕР»РёС‡РµСЃС‚РІРѕ СЃС‚СѓРґРµРЅС‚РѕРІ 
.RE
.PP

.SS "void RatesPage::setAllStudents (QJsonArray docArr)\fC [private]\fP"

.PP
setAllStudents - СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚ СЃС‚СѓРґРµРЅС‚РѕРІ РІ РєРѕРјР±Рѕ-Р±РѕРєСЃ 
.PP
\fBАргументы\fP
.RS 4
\fIdocArr\fP - СЃРїРёСЃРѕРє СЃС‚СѓРґРµРЅС‚РѕРІ 
.RE
.PP

.SS "void RatesPage::setData (QComboBox * comboBox, QJsonArray arr)\fC [private]\fP"

.PP
setData СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚ РґР°РЅРЅС‹Рµ РєРѕРјР±Рѕ-Р±РѕРєСЃ 
.PP
\fBАргументы\fP
.RS 4
\fIcomboBox\fP - РєРѕРјР±Рѕ-Р±РѕРєСЃ, РІ РєРѕС‚РѕСЂС‹Р№ СѓСЃС‚Р°РЅР°РІР»РёРІР°СЋС‚СЃСЏ Р·РЅР°С‡РµРЅРёСЏ 
.br
\fIarr\fP - РЅР°Р±РѕСЂ РґР°РЅРЅС‹С… РґР»СЏ СѓСЃС‚РЅРѕРІРєРё 
.RE
.PP

.SS "void RatesPage::setGroupsForAddLesson (QJsonArray docArr)\fC [private]\fP"

.SS "void RatesPage::setRates (QString rate)\fC [private]\fP"

.SS "void RatesPage::setRateToStudentInGenerallist (QString rate, int student_Id, int lesson_Id)\fC [private]\fP, \fC [slot]\fP"

.PP
setRateToStudentInGenerallist - РЈСЃС‚Р°РЅР°РІР»СЏРІР°РµС‚ Р±Р°Р»Р» СЃС‚СѓРґРµРЅС‚Сѓ 
.PP
\fBАргументы\fP
.RS 4
\fIrate\fP - СЃР°Рј Р±Р°Р»Р» 
.br
\fIstudent_Id\fP - РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ СЃС‚СѓРґРµРЅС‚Р°, РєРѕС‚РѕСЂРѕРјСѓ СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚СЃСЏ Р±Р°Р»Р» 
.br
\fIlesson_Id\fP - РїРµСЂРІРёС‡РЅС‹Р№ РєР»СЋС‡ Р·Р°РЅСЏС‚РёСЏ, Р·Р° РєРѕС‚РѕСЂРѕРµ СѓСЃС‚Р°РЅР°РІР»РёРІР°РµС‚СЃСЏ Р±Р°Р»Р» 
.RE
.PP

.SS "void RatesPage::setStudents (QJsonArray docAr_students, QJsonArray docAr_couse)\fC [private]\fP"

.SS "void RatesPage::sockDisc ()\fC [private]\fP, \fC [slot]\fP"

.SS "void RatesPage::sockReady ()\fC [private]\fP, \fC [slot]\fP"

.SH "Данные класса"
.PP 
.SS "\fBInput\fP RatesPage::input_window\fC [private]\fP"

.SS "QTcpSocket* RatesPage::socket =nullptr"

.SS "Ui::RatesPage* RatesPage::ui\fC [private]\fP"


.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(Клиентская часть) из исходного текста\&.
