.TH "Documents/student_rates_client/rateswindow.h" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/student_rates_client/rateswindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QTcpSocket>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QJsonParseError>\fP
.br
\fC#include <QStandardItem>\fP
.br
\fC#include <QJsonArray>\fP
.br
\fC#include 'input\&.h'\fP
.br
\fC#include <QtSql/QtSql>\fP
.br
\fC#include <QTableWidget>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBRatesPage\fP"
.br
.RI "The \fBRatesPage\fP class\&. "
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(Клиентская часть) из исходного текста\&.
