.TH "Documents/student_rates_client/rateswindow.cpp" 3 "Вт 29 Дек 2020" "Приложение по учету успеваемости студентов(Клиентская часть)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Documents/student_rates_client/rateswindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'rateswindow\&.h'\fP
.br
\fC#include 'ui_rateswindow\&.h'\fP
.br

.SH "Автор"
.PP 
Автоматически создано Doxygen для Приложение по учету успеваемости студентов(Клиентская часть) из исходного текста\&.
